name: "SECGPT Vercel Automated Deployment"

on: 
  push:
    branches: ["main"]

jobs: 
  deploy:

    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses:: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Login to Vercel
        env:

          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel login --token $VERCEL_TOKEN

      - name: Deploy SECGPT to Vercel
        run: vercel --prod